// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://goyoosylyxwygklqoxvd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdveW9vc3lseXh3eWdrbHFveHZkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDYwMzIxNTksImV4cCI6MjA2MTYwODE1OX0.fBeIdN8DphyXN_BVtQsAG7yfVGpf5VyyaoZo1drkJmM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);